# Generated by Django 4.2.5 on 2023-10-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_of_creation',), 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
